---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages/en
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - dental-tourism
  - blog-post
- type: directory
  path: src/pages
  label: Paginas
  create: all
  match: "**/*"
  exclude: "/en/**/*"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run develop -p 8080 -H 0.0.0.0
